### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rbrtslmn** [Codingspezis/metal-only#62]
App-Version: 0.4.121
Android 4.31
Galaxy S3 (m0)
```
java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
at java.lang.String.startEndAndLength(String.java:583)
at java.lang.String.substring(String.java:1464)
at com.codingspezis.android.metalonly.player.utils.jsonapi.Stats.getGenre(Stats.java:88)
at com.codingspezis.android.metalonly.player.MainActivity$1.run(MainActivity.java:120)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by ironjan** [comment]
The genre is part of the show name. An example for a show name is ```Einmal Musik bitte, mit allem! (Mixed Rock & Metal)```. The genre is the part between ```(``` and ```)```. 

Current code in master:
```java
public String getGenre() {
  if (genre.length() == 0) {
    int startGenre = sendung.indexOf("(") + 1;
    int endGenre = sendung.indexOf(")");
    genre = sendung.substring(startGenre, endGenre);
  }
  return genre;
}
```

Potential bad strings that break stuff:
 * ```Name (```
 * ```Name Genre)```
 * ```()```
 * ```Name ()```
