### ISSUE TITLE
Regular crashes reported on Google Play because of StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ironjan** [Codingspezis/metal-only#90]
Version: 0.14.4

Reported on different Android-Versions and different devices.

**Stacktrace:**

```
java.lang.StringIndexOutOfBoundsException: length=36; regionStart=0; regionLength=-1
	at java.lang.String.startEndAndLength(String.java:504)
	at java.lang.String.substring(String.java:1333)
	at com.codingspezis.android.metalonly.player.utils.jsonapi.Stats.getGenre(Stats.java:82)
	at com.codingspezis.android.metalonly.player.MainActivity$1.run(MainActivity.java:123)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by ironjan** [comment]
Duplicate of #62
